version: '3.2.0'
services:
  consul-server:
    container_name: consul-server
    image: consul:latest
    ports:
      - 8500:8500
    command: 'agent -server -bootstrap-expect=1 -ui -bind=0.0.0.0 -client=0.0.0.0'
    networks:
      - microservices-network
  gateway-service:
    container_name: gateway-service
    image: gateway-service:latest
    ports:
      - 9999:9999
    links:
      - consul-server
    networks:
      - microservices-network
  config-service:
    container_name: config-service
    image: config-service:latest
    ports:
      - 9800:9800
    links:
      - consul-server
    networks:
      - microservices-network
  auth-service:
    container_name: auth-service
    image: auth-service:latest
    ports:
      - 9000:9000
    links:
      - consul-server
    networks:
      - microservices-network
  about-service:
    container_name: about-service
    image: about-service:latest
    ports:
      - 9001:9001
    links:
      - consul-server
    networks:
      - microservices-network
  career-service:
    container_name: career-service
    image: career-service:latest
    ports:
      - 9002:9002
    links:
      - consul-server
    networks:
      - microservices-network
  contact-service:
    container_name: contact-service
    image: contact-service:latest
    ports:
      - 9003:9003
    links:
      - consul-server
    networks:
      - microservices-network
  contact-home-service:
    container_name: home-service
    image: home-service:latest
    ports:
      - 9004:9004
    links:
      - consul-server
    networks:
      - microservices-network
  offers-service:
    container_name: offers-service
    image: offers-service:latest
    ports:
      - 9005:9005
    links:
      - consul-server
    networks:
      - microservices-network
networks:
  microservices-network:
    driver: bridge